apiVersion: apps/v1
kind: Deployment
metadata:
  name: filemicroservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filemicroservice-app
  template:
    metadata:
      labels:
        app: filemicroservice-app
    spec:
      containers:
        - name: filemicroservice-app
          image: bryanaafjes/feedbacktrx-filehandlermicroservice:latest
          ports:
            - containerPort: 80
          env:
            - name: AzureBlobStorage__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: fileservice-env-secret
                  key: ConnectionString
            - name: AzureBlobStorage__ContainerName
              valueFrom:
                secretKeyRef:
                  name: fileservice-env-secret
                  key: ContainerName
            - name: RabbitMQ__Uri
              valueFrom:
                secretKeyRef:
                  name: fileservice-env-secret
                  key: RabbitURI
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: fileservice-env-secret
                  key: RabbitUsername
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: fileservice-env-secret
                  key: RabbitPassword
---
apiVersion: v1
kind: Service
metadata:
  name: filemicroservice-service
spec:
  selector:
    app: filemicroservice-app
  ports:
    - port: 80