name: ASP.NET Core Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test

  build-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: feedbacktrx.filehandlermicroservice/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/feedbacktrx-filehandlermicroservice:latest

  deploy:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Generate kube configuration
        run: |
          mkdir ~/.kube
          touch ~/.kube/config
          echo "${{ secrets.KUBE_CONF }}" >> ~/.kube/config

      # CHANGE THIS TO ADD SECRETS FOR BLOBSTORAGE
      # - name: Create secrets
      #   run: |
      #     kubectl delete configmap env-configmap --ignore-not-found
      #     kubectl create configmap env-configmap --from-literal=env.js=${{ secrets.ENV_JS}}

      - name: Deploy ClamAV
        run: kubectl apply -f feedbacktrx.filehandlermicroservice/kubernetes/clamav.yaml

      - name: Deploy application
        run: kubectl apply -f feedbacktrx.filehandlermicroservice/kubernetes/deployment.yaml

      - name: Restart deployment ClamAV
        run: kubectl rollout restart deploy clamav

      - name: Restart deployment File Handler
        run: kubectl rollout restart deploy filemicroservice-app
